// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TPTMapping.Migrations
{
    [DbContext(typeof(AnimalContext))]
    partial class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Pet", b =>
                {
                    b.HasBaseType("Animal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Cat", b =>
                {
                    b.HasBaseType("Pet");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("Dog", b =>
                {
                    b.HasBaseType("Pet");

                    b.Property<string>("FavoriteToy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Dogs");
                });
#pragma warning restore 612, 618
        }
    }
}
